openapi: 3.0.0

info:
  title: Syfo-MacGyver
  description: API for syfo-MacGyver. Husk 책 velge riktig url :)
  version: 1.0.0
servers:
  - url: 'https://macgyver.dev.intern.nav.no'
  - url: 'https://macgyver.intern.nav.no'
paths:
  /api/papirsykmelding/{sykmeldingId}/periode:
    post:
      operationId: updatePeriode
      tags:
        - Papirsykmelding
      security:
        - bearerAuth: [ ]
      summary: Endre periode (fom og tom) for mottatt sykmelding som har maks en periode.
      description: OBS! Denne vil overskrive annen informasjon, f.eks. medisinsk 책rsak, p책 perioden! M책 kun brukes for helt enkle tilfeller.
      parameters:
        - $ref: '#/components/parameters/sykmeldingId'
      requestBody:
        $ref: '#/components/requestBodies/PeriodelisteDTORequest'
      responses:
        '200':
          description: Ok
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

components:
  requestBodies:
    PeriodelisteDTORequest:
      description: "Riktig periodeliste for sykmeldingen"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PeriodelisteDTO'
  parameters:
    sykmeldingId:
      description: Id for sykmelding som skal rettes
      name: sykmeldingId
      in: path
      required: true
      schema:
        type: string
      example: '123'
  schemas:
    Date:
      type: string
      format: date
      example: '2020-12-15'
    PeriodelisteDTO:
      type: object
      required:
        - periodeliste
      properties:
        periodeliste:
          type: array
          items:
            $ref: '#/components/schemas/Periode'
    Periode:
      type: object
      required:
        - fom
        - tom
        - reisetilskudd
      properties:
        fom:
          $ref: '#/components/schemas/Date'
        tom:
          $ref: '#/components/schemas/Date'
        aktivitetIkkeMulig:
          $ref: '#/components/schemas/AktivitetIkkeMulig'
        avventendeInnspillTilArbeidsgiver:
          type: string
        behandlingsdager:
          type: integer
        gradert:
          $ref: '#/components/schemas/Gradert'
        reisetilskudd:
          type: boolean
    AktivitetIkkeMulig:
      type: object
      properties:
        medisinskArsak:
          $ref: '#/components/schemas/MedisinskArsak'
        arbeidsrelatertArsak:
          $ref: '#/components/schemas/ArbeidsrelatertArsak'
    MedisinskArsak:
      type: object
      properties:
        beskrivelse:
          type: string
        arsak:
          type: array
          items:
            $ref: '#/components/schemas/MedisinskArsakType'
    MedisinskArsakType:
      type: string
      enum: [ TILSTAND_HINDRER_AKTIVITET, AKTIVITET_FORVERRER_TILSTAND, AKTIVITET_FORHINDRER_BEDRING, ANNET ]
    ArbeidsrelatertArsak:
      type: object
      properties:
        beskrivelse:
          type: string
        arsak:
          type: array
          items:
            $ref: '#/components/schemas/ArbeidsrelatertArsakType'
    ArbeidsrelatertArsakType:
      type: string
      enum: [ MANGLENDE_TILRETTELEGGING, ANNET ]
    Gradert:
      type: object
      properties:
        grad:
          type: integer
          minimum: 0
          maximum: 100
        reisetilskudd:
          type: boolean

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: [ ]
