openapi: 3.0.0

info:
  title: Syfo-MacGyver
  description: API for syfo-MacGyver.
  version: 1.0.0
servers:
  - url: 'https://macgyver.dev.intern.nav.no'
paths:
  /api/papirsykmelding/{sykmeldingId}/periode:
    post:
      operationId: updatePeriode
      tags:
        - Papirsykmelding
      security:
        - bearerAuth: []
      summary: Endre periode (fom og tom for mottatt papirsykmelding som har maks en periode). OBS! Overskriver annen informasjon på perioden, f.eks. medisinsk årsak!
      parameters:
        - $ref: '#/components/parameters/sykmeldingId'
      requestBody:
        $ref: '#/components/requestBodies/PeriodeDTORequest'
      responses:
        '200':
          description: Ok
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

components:
  requestBodies:
    PeriodeDTORequest:
      description: "Riktig periode for sykmeldingen"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PeriodeDTO'
  parameters:
    sykmeldingId:
      description: Id for sykmelding som skal rettes
      name: sykmeldingId
      in: path
      required: true
      schema:
        type: string
      example: '123'
  schemas:
    Date:
      type: string
      format: date
    PeriodeDTO:
      type: object
      required:
        - fom
        - tom
      properties:
        fom:
          $ref: '#/components/schemas/Date'
        tom:
          $ref: '#/components/schemas/Date'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
