openapi: 3.0.0

info:
  title: Syfo-MacGyver
  description: API for syfo-MacGyver. Husk å velge riktig url! :)
  version: 1.0.0
servers:
  - url: 'https://macgyver.dev.intern.nav.no'
  - url: 'https://macgyver.intern.nav.no'
paths:
  /api/sykmelding/{sykmeldingId}:
    patch:
      operationId: patchSykmelding
      tags:
        - Sykmelding
      security:
        - bearerAuth: [ ]
      summary: Endre fnr for en gitt sykmelding
      description: Oppdaterer sykemeldts fnr for en gitt sykmelding i SyfoSmRegister og SyfoService
      parameters:
        - $ref: '#/components/parameters/sykmeldingId'
      requestBody:
        $ref: '#/components/requestBodies/PeriodelisteDTORequest'
      responses:
        '200':
          description: Ok
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /api/papirsykmelding/{sykmeldingId}/periode:
    post:
      operationId: updatePeriode
      tags:
        - Papirsykmelding
      security:
        - bearerAuth: [ ]
      summary: Endre periodelisten for en gitt sykmelding
      description: OBS! Denne vil overskrive alle eksisterende sykmeldingsperioder for denne sykmeldingen!!
      parameters:
        - $ref: '#/components/parameters/sykmeldingId'
      requestBody:
        $ref: '#/components/requestBodies/PeriodelisteDTORequest'
      responses:
        '200':
          description: Ok
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /api/papirsykmelding/{sykmeldingId}/behandletdato:
    post:
      operationId: updateBehandletDato
      tags:
        - Papirsykmelding
      security:
        - bearerAuth: [ ]
      summary: Endre behandletdato for en gitt sykmelding
      description: Endre behandletdato for en gitt sykmelding i smregister og syfoservice
      parameters:
        - $ref: '#/components/parameters/sykmeldingId'
      requestBody:
        $ref: '#/components/requestBodies/BehandletDatoDTORequest'
      responses:
        '200':
          description: Ok
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

components:
  requestBodies:
    SykmeldingMap:
      description: "Sykmelding representert som et Map"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PeriodelisteDTO'
    PeriodelisteDTORequest:
      description: "Riktig periodeliste for sykmeldingen"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PeriodelisteDTO'
    BehandletDatoDTORequest:
      description: "Riktig behandletdato for sykmeldingen"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BehandletDatoDTO'
  parameters:
    sykmeldingId:
      description: Id for sykmelding som skal rettes
      name: sykmeldingId
      in: path
      required: true
      schema:
        type: string
      example: '123'
  schemas:
    SykmeldingMap:
      type: object
      required:
        - fnr
      properties:
        fnr:
          type: string
          minLength: 11
          maxLength: 11
    Date:
      type: string
      format: date
      example: '2020-12-15'
    PeriodelisteDTO:
      type: object
      required:
        - periodeliste
      properties:
        periodeliste:
          type: array
          items:
            $ref: '#/components/schemas/Periode'
    Periode:
      type: object
      required:
        - fom
        - tom
        - reisetilskudd
      properties:
        fom:
          $ref: '#/components/schemas/Date'
        tom:
          $ref: '#/components/schemas/Date'
        aktivitetIkkeMulig:
          $ref: '#/components/schemas/AktivitetIkkeMulig'
        avventendeInnspillTilArbeidsgiver:
          type: string
        behandlingsdager:
          type: integer
        gradert:
          $ref: '#/components/schemas/Gradert'
        reisetilskudd:
          type: boolean
    AktivitetIkkeMulig:
      type: object
      properties:
        medisinskArsak:
          $ref: '#/components/schemas/MedisinskArsak'
        arbeidsrelatertArsak:
          $ref: '#/components/schemas/ArbeidsrelatertArsak'
    MedisinskArsak:
      type: object
      properties:
        beskrivelse:
          type: string
        arsak:
          type: array
          items:
            $ref: '#/components/schemas/MedisinskArsakType'
    MedisinskArsakType:
      type: string
      enum: [ TILSTAND_HINDRER_AKTIVITET, AKTIVITET_FORVERRER_TILSTAND, AKTIVITET_FORHINDRER_BEDRING, ANNET ]
    ArbeidsrelatertArsak:
      type: object
      properties:
        beskrivelse:
          type: string
        arsak:
          type: array
          items:
            $ref: '#/components/schemas/ArbeidsrelatertArsakType'
    ArbeidsrelatertArsakType:
      type: string
      enum: [ MANGLENDE_TILRETTELEGGING, ANNET ]
    Gradert:
      type: object
      properties:
        grad:
          type: integer
          minimum: 0
          maximum: 100
        reisetilskudd:
          type: boolean
    BehandletDatoDTO:
      type: object
      required:
        - behandletDato
      properties:
        behandletDato:
          $ref: '#/components/schemas/Date'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: [ ]
