apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfoservice-data-syfosmregister
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 3
    max: 3
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 2048m
      memory: 4Gi
    requests:
      cpu: 2048m
      memory: 4Gi
  kafka:
    pool: nav-prod
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/prod/srvsyfoservice-dat
        mountPath: /secrets/serviceuser
      - kvPath: oracle/data/prod/creds/syfoservice-user
        mountPath: /secrets/syfoservice/credentials
      - kvPath: oracle/data/prod/config/syfoservice
        mountPath: /secrets/syfoservice/config
      - kvPath: oracle/data/prod/creds/eia_p-user
        mountPath: /secrets/eia/credentials
      - kvPath: oracle/data/prod/config/eia_p
        mountPath: /secrets/eia/config
      - kvPath: /azuread/data/prod/creds/syfoservice-data-syfosmregister
        mountPath: /secrets/azuread/syfoservice-data-syfosmregister
      - kvPath: /kv/prod/fss/syfoservice-data-syfosmregister/teamsykmelding
        mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
  ingresses:
    - "https://syfoservice-data-syfosmregister.nais.adeo.no"
    - "https://macgyver.intern.nav.no"
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SASL_SSL://a01apvl00145.adeo.no:8443,SASL_SSL://a01apvl00146.adeo.no:8443,SASL_SSL://a01apvl00147.adeo.no:8443,SASL_SSL://a01apvl00149.adeo.no:8443
    - name: SYFOSMREGISTER_DB_URL
      value: jdbc:postgresql://fsspgdb.adeo.no:5432/syfosmregister
    - name: PALE_2_REGISTER_DB_URL
      value: jdbc:postgresql://A01DBVL011.adeo.no:5432/pale-2-register
    - name: SPARENAPROXY_DB_URL
      value: jdbc:postgresql://A01DBVL014.adeo.no:5432/sparenaproxy
    - name: MOUNT_PATH_VAULT
      value: /postgresql/prod-fss
    - name: LAST_INDEX_EIA
      value: "33745516"
    - name: LAST_INDEX_SYFOSERVICE
      value: "0"
    - name: LAST_INDEX_SYFOSMREGISTER
      value: "2016-01-01"
    - name: LAST_INDEX_BACKUP
      value: "2019-05-01"
    - name: LAST_INDEX_SPARENAPROXY
      value: "2020-06-20"
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.nais.adeo.no/graphql
    - name: SECURITY_TOKEN_SERVICE_URL
      value: https://security-token-service.nais.adeo.no/rest/v1/sts/token
    - name: KAFKA_CLIENT_ID
      value: syfoservice-data-syfosmregister
    - name: LAST_INDEX_NL_SYFOSERVICE
      value: "0"
    - name: OPPGAVEBEHANDLING_URL
      value: https://oppgave.nais.adeo.no/api/v1/oppgaver
