apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfoservice-data-syfosmregister
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 1024m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 128Mi
  kafka:
    pool: nav-dev
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/dev/srvsyfoservice-dat
        mountPath: /secrets/serviceuser
      - kvPath: oracle/data/dev/creds/syfoservice_q1-user
        mountPath: /secrets/syfoservice/credentials
      - kvPath: oracle/data/dev/config/syfoservice_q1
        mountPath: /secrets/syfoservice/config
      - kvPath: oracle/data/dev/creds/eia2_q1-user
        mountPath: /secrets/eia/credentials
      - kvPath: oracle/data/dev/config/eia2_q1
        mountPath: /secrets/eia/config
      - kvPath: /azuread/data/dev/creds/syfoservice-data-syfosmregister
        mountPath: /secrets/azuread/syfoservice-data-syfosmregister
      - kvPath: /kv/preprod/fss/syfoservice-data-syfosmregister/teamsykmelding
        mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
  ingresses:
    - "https://syfoservice-data-syfosmregister.nais.preprod.local"
    - "https://macgyver.dev.intern.nav.no"
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: SYFOSMREGISTER_DB_URL
      value: jdbc:postgresql://B27DBVL003.preprod.local:5432/syfosmregister
    - name: PALE_2_REGISTER_DB_URL
      value: jdbc:postgresql://b27dbvl013.preprod.local:5432/pale-2-register
    - name: SPARENAPROXY_DB_URL
      value: jdbc:postgresql://b27dbvl016.preprod.local:5432/sparenaproxy
    - name: MOUNT_PATH_VAULT
      value: /postgresql/preprod-fss
    - name: LAST_INDEX_EIA
      value: "161278"
    - name: LAST_INDEX_SYFOSERVICE
      value: "114402"
    - name: LAST_INDEX_SYFOSMREGISTER
      value: "2016-06-03"
    - name: LAST_INDEX_BACKUP
      value: "2019-05-01"
    - name: LAST_INDEX_SPARENAPROXY
      value: "2020-06-20"
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.nais.preprod.local/graphql
    - name: SECURITY_TOKEN_SERVICE_URL
      value: https://security-token-service.nais.preprod.local/rest/v1/sts/token
    - name: KAFKA_CLIENT_ID
      value: syfoservice-data-syfosmregister
    - name: LAST_INDEX_NL_SYFOSERVICE
      value: "100000000"
