apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfoservice-data-syfosmregister
  namespace: default
  labels:
    team: {{team}}
spec:
  image: "docker.pkg.github.com/navikt/syfoservice-data-syfosmregister:{{tag}}"
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/dev/srvsyfoservice-dat
        mountPath: /secrets/serviceuser
      - kvPath: oracle/data/dev/creds/syfoservice_q1-user
        mountPath: /secrets/credentials
      - kvPath: oracle/data/dev/config/syfoservice_q1
        mountPath: /secrets/config
  webproxy: true
  ingresses:
    - "https://syfoservice-data-syfosmregister.nais.preprod.local"
